import { styled, Box } from '@mui/system';

const VolumeSliderBox = styled(Box)(() => ({
  position: 'absolute',
  top: 'calc(-105px)',
  left: '50%',
  transform: 'translateX(-50%)',
  background: '#ffffff',
  borderRadius: '4px',
  display: 'flex',
  justifyContent: 'center',
  padding: '10px 0',
  width: '30px',
  height: '100px',
  boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
  transition: 'all 0.3s ease-in-out',
  zIndex: '1',
  '&:before': {
    content: '""',
    position: 'absolute',
    bottom: '-16px',
    left: 'calc(50%)',
    transform: 'translateX(-50%)',
    width: '0',
    height: '0',
    zIndex: '-1',
    borderLeft: '6px solid transparent',
    borderRight: '6px solid transparent',
    borderBottom: '6px solid transparent',
    borderTop: '6px solid rgba(0, 0, 0, 0.1)',
    filter: 'blur(3px)',
  },
  '&:after': {
    content: '""',
    position: 'absolute',
    bottom: '-10px',
    left: '50%',
    transform: 'translateX(-50%)',
    width: '0',
    height: '0',
    zIndex: '-1',
    borderLeft: '5px solid transparent',
    borderRight: '5px solid transparent',
    borderBottom: '5px solid transparent',
    borderTop: '5px solid #ffffff',
  },
}));

export { VolumeSliderBox };
